- name: kubectl
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # Linux

    - name: Add Kubernetes APT package key
      become: yes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      when: not is_mac

    - name: Add Kubernetes APT package repository
      become: yes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        filename: kubernetes
        update_cache: no
      register: apt_repository
      when: not is_mac

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install kubectl (Linux)
      become: yes
      apt:
        package: kubectl
      when: not is_mac

    # macOS

    - name: Install bash completion support
      homebrew:
        name: bash-completion
      register: bash_completion
      when: is_mac

    - name: Add bash completion support to shell
      lineinfile:
        path: ~/.bashrc
        line: source $(brew --prefix)/etc/bash_completion
      when: bash_completion.changed

    - name: Install kubectl (macOS)
      homebrew:
        name: kubectl
      when: is_mac

    # Common

    - name: Enable bash completion for kubectl
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Enable kubectl auto-complete"
        block: |
          eval "$(kubectl completion bash)"
